- name: deploy container on remote server
  hosts: deepschool_host
  tasks:
    - name: create workdir
      file:
        path: '{{ workdir }}'
        state: directory
        owner: '{{ ansible_user }}'
      tags: [ 'prepare' ]

    - name: create pull script
      template:
        dest: '{{ workdir }}/pull.sh'
        src: 'templates/pull.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: create run script
      template:
        dest: '{{ workdir }}/run.sh'
        src: 'templates/run.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: pull docker image
      command: '{{ workdir }}/pull.sh'
      tags: [ 'pull' ]

    - name: run new docker container
      command: '{{ workdir }}/run.sh'
      tags: [ 'deploy' ]
